export const designTokens = {
  color: {
    background: "#F0FDFA",
    surface: "#FFFFFF",
    surfaceMuted: "#CCFBF1",
    surfaceRaised: "#F8FFFD",
    brand: "#0D9488",
    brandSecondary: "#14B8A6",
    brandSoft: "#CCFBF1",
    accent: "#EA580C",
    accentSoft: "#FFEDD5",
    textPrimary: "#134E4A",
    textSecondary: "#2D6F6A",
    textMuted: "#5E8D88",
    border: "#99F6E4",
    borderSubtle: "#D5F7EF",
    success: "#047857",
    successSoft: "#DCFCE7",
    warning: "#B45309",
    warningSoft: "#FEF3C7",
    danger: "#B42318",
    dangerSoft: "#FEE4E2",
  },
  spacing: {
    xxs: "8rpx",
    xs: "12rpx",
    sm: "16rpx",
    md: "24rpx",
    lg: "32rpx",
    xl: "40rpx",
    xxl: "56rpx",
    pageX: "32rpx",
    pageTop: "56rpx",
    bottomNavHeight: "128rpx",
  },
  radius: {
    sm: "10rpx",
    md: "18rpx",
    card: "24rpx",
    pill: "999rpx",
  },
  shadow: {
    card: "0 8rpx 22rpx rgba(19, 78, 74, 0.06)",
    nav: "0 -6rpx 18rpx rgba(19, 78, 74, 0.08)",
  },
  fontSize: {
    caption: "22rpx",
    body: "28rpx",
    bodyLarge: "32rpx",
    title: "44rpx",
    hero: "56rpx",
  },
  component: {
    touchTarget: "96rpx",
    inputHeight: "96rpx",
    bottomNavHeight: "128rpx",
  },
} as const;

export type DesignTokens = typeof designTokens;
